{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-jvm",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.5.1.jar",
          "url": "core-crypto-jvm-0.5.1.jar",
          "size": 7551084,
          "sha512": "20400b77303c1e91f00b047d227a8b8a857fac513d1c7b3a8309509df43590e28b964c71e0f1e617a08dc6fb41934f54faed24995508bffd5bf973c40ddade04",
          "sha256": "f42152bc66454bc8ede01e582a840d556b72c3afd2440fbd4660760c3414af9e",
          "sha1": "1a129839781793f967cce93fafda828850342d70",
          "md5": "a32229e3dec60612ea488fe50deec7a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.5.1.jar",
          "url": "core-crypto-jvm-0.5.1.jar",
          "size": 7551084,
          "sha512": "20400b77303c1e91f00b047d227a8b8a857fac513d1c7b3a8309509df43590e28b964c71e0f1e617a08dc6fb41934f54faed24995508bffd5bf973c40ddade04",
          "sha256": "f42152bc66454bc8ede01e582a840d556b72c3afd2440fbd4660760c3414af9e",
          "sha1": "1a129839781793f967cce93fafda828850342d70",
          "md5": "a32229e3dec60612ea488fe50deec7a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-crypto-jvm-0.5.1-sources.jar",
          "url": "core-crypto-jvm-0.5.1-sources.jar",
          "size": 7415487,
          "sha512": "54903a02d0e2d2444a5f545b02e46989ba19fabe4b4a94e71101f2259b73337dd091c66c9493fa80376b6b5832d35d58d2f7d94219bcd6617f2dd98252a40c63",
          "sha256": "ee0e727a7849b2880c8ca59c4cdedaed30ea4079739550c70ef3784a495c43d9",
          "sha1": "9661363e70167f96c955ba8ab357de90649070fd",
          "md5": "7fef3544b3c63fced55fe4b8620c7102"
        }
      ]
    }
  ]
}
