{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-android",
    "version": "0.6.0-pre1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.6.0-pre1.aar",
          "url": "core-crypto-android-0.6.0-pre1.aar",
          "size": 14369980,
          "sha512": "ab222a83d25362da14a8e4ce82d50279603f47801196ad29b334edbbb8e2553107c2de8f174345929b4c1c631973fefa048adc5c772a028000bc424057d60a92",
          "sha256": "6de8b9fbd5cd6b5367889b427df6e55ee2a7d91c98892499d312c39c67b20cb0",
          "sha1": "42b3f41ab6493bedb13235f110e2e9ef550d5790",
          "md5": "d10928572a0bc67629972d1afbca125b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.6.0-pre1.aar",
          "url": "core-crypto-android-0.6.0-pre1.aar",
          "size": 14369980,
          "sha512": "ab222a83d25362da14a8e4ce82d50279603f47801196ad29b334edbbb8e2553107c2de8f174345929b4c1c631973fefa048adc5c772a028000bc424057d60a92",
          "sha256": "6de8b9fbd5cd6b5367889b427df6e55ee2a7d91c98892499d312c39c67b20cb0",
          "sha1": "42b3f41ab6493bedb13235f110e2e9ef550d5790",
          "md5": "d10928572a0bc67629972d1afbca125b"
        }
      ]
    }
  ]
}
