{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-android",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.0.1.aar",
          "url": "core-crypto-android-0.0.1.aar",
          "size": 92610776,
          "sha512": "46f181afc6214714a23ac4bb21e36115c8fab9f7b62b371e58518bdf7cd78eb246181b93b08781ea94eb096613773f72f15c27513f8bd37a081b1d37c585e9ad",
          "sha256": "0caaa54ce5e55aa476510670007214104884becf3a68602da3beabe4a05a3660",
          "sha1": "50f9da7e7cf31efb6ce17732779d33740343b3a9",
          "md5": "1e6802e0956635f24395802b6196c616"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.0.1.aar",
          "url": "core-crypto-android-0.0.1.aar",
          "size": 92610776,
          "sha512": "46f181afc6214714a23ac4bb21e36115c8fab9f7b62b371e58518bdf7cd78eb246181b93b08781ea94eb096613773f72f15c27513f8bd37a081b1d37c585e9ad",
          "sha256": "0caaa54ce5e55aa476510670007214104884becf3a68602da3beabe4a05a3660",
          "sha1": "50f9da7e7cf31efb6ce17732779d33740343b3a9",
          "md5": "1e6802e0956635f24395802b6196c616"
        }
      ]
    }
  ]
}
