{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-android",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.0.1.aar",
          "url": "core-crypto-android-0.0.1.aar",
          "size": 13115157,
          "sha512": "db3329e019ad30ce6d5e96bf1bf4a3c74b2d5864197545437d764529fab5127337893c85fb75be9c200f232f7eca9dd9887a2fef6ba367f173a8ecd2eef027a3",
          "sha256": "d8ec6531a0d077e972b5ae496ef41fd0407e2627ab50dc57eaff35d3f409f635",
          "sha1": "115b40db05d2e7b03653bec8720b4629d5674760",
          "md5": "f7aeaf4534fdf6699bd1124e34180362"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.0.1.aar",
          "url": "core-crypto-android-0.0.1.aar",
          "size": 13115157,
          "sha512": "db3329e019ad30ce6d5e96bf1bf4a3c74b2d5864197545437d764529fab5127337893c85fb75be9c200f232f7eca9dd9887a2fef6ba367f173a8ecd2eef027a3",
          "sha256": "d8ec6531a0d077e972b5ae496ef41fd0407e2627ab50dc57eaff35d3f409f635",
          "sha1": "115b40db05d2e7b03653bec8720b4629d5674760",
          "md5": "f7aeaf4534fdf6699bd1124e34180362"
        }
      ]
    }
  ]
}
