{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-jvm",
    "version": "0.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.5.2.jar",
          "url": "core-crypto-jvm-0.5.2.jar",
          "size": 7550312,
          "sha512": "13d82c9a99b94e31ed96890b530c66742fec695c48cca4bd39770e292702b7e30ca2a9a42287d43c5bd3274e5898f54bb4ca614e5d0a6be77649320e1f969c20",
          "sha256": "0d959f0b1fa8a760cd3c4319aff82291e3bd107a83d9257e042c30d41c587331",
          "sha1": "18d1eb89be352b56b53581d5dbf2e34da7b5c9d2",
          "md5": "c86340effd8f9350e1af79dd80fe613c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.5.2.jar",
          "url": "core-crypto-jvm-0.5.2.jar",
          "size": 7550312,
          "sha512": "13d82c9a99b94e31ed96890b530c66742fec695c48cca4bd39770e292702b7e30ca2a9a42287d43c5bd3274e5898f54bb4ca614e5d0a6be77649320e1f969c20",
          "sha256": "0d959f0b1fa8a760cd3c4319aff82291e3bd107a83d9257e042c30d41c587331",
          "sha1": "18d1eb89be352b56b53581d5dbf2e34da7b5c9d2",
          "md5": "c86340effd8f9350e1af79dd80fe613c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-crypto-jvm-0.5.2-sources.jar",
          "url": "core-crypto-jvm-0.5.2-sources.jar",
          "size": 7414715,
          "sha512": "9e194f4c6844264ec5ff85b884175cd209bdb1b874906aee7ce5f95f4335646feeb4804a637d59080259a4b1c237e270812196abadf10ed94966d6983caaf99d",
          "sha256": "fe36e3b4a90aec2226f5480a0ded76c18cfc6d3ee4b86e26fc98f0f8227030b6",
          "sha1": "5e8fb761399b07eb1b6b4c8a017f0b6fb4d1fd04",
          "md5": "fc42deb8b691276c2a892e60f0d91cbb"
        }
      ]
    }
  ]
}
