{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-android",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.5.1.aar",
          "url": "core-crypto-android-0.5.1.aar",
          "size": 13562234,
          "sha512": "f354aa6c7a9dc7031bfdf72731f80df2a764b1a6a534006bfb39a320786a566a84e4ab3261fda8337c0412ae11e1f4d5a3a73ade17da0df84e11658116cc091c",
          "sha256": "59679b4a798d3fa32f70ffc4bc47c3d292575e89a7c1469ab3acac15c462b08b",
          "sha1": "d6bf6b5e74a697d8532550c50e7b9cf394929d22",
          "md5": "0b8d13201a3ff148a8f84187ab2c8cc2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-android-0.5.1.aar",
          "url": "core-crypto-android-0.5.1.aar",
          "size": 13562234,
          "sha512": "f354aa6c7a9dc7031bfdf72731f80df2a764b1a6a534006bfb39a320786a566a84e4ab3261fda8337c0412ae11e1f4d5a3a73ade17da0df84e11658116cc091c",
          "sha256": "59679b4a798d3fa32f70ffc4bc47c3d292575e89a7c1469ab3acac15c462b08b",
          "sha1": "d6bf6b5e74a697d8532550c50e7b9cf394929d22",
          "md5": "0b8d13201a3ff148a8f84187ab2c8cc2"
        }
      ]
    }
  ]
}
