{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-jvm",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.0.1.jar",
          "url": "core-crypto-jvm-0.0.1.jar",
          "size": 6925102,
          "sha512": "27eb512ada7602293b2ab0edf190f3d6cb0e1a69d4a31675b54b4293086ef7b1ffc34b99bd8f36e951480c358a72f2d4fce284a5786518e13568b9c0110239fb",
          "sha256": "a6b4ecd10835e2cc5ccdc600df388b57ca3e3e5a591a4806c9803652c86306af",
          "sha1": "beedb023c96228d8c7f15c954d4680453f32d3db",
          "md5": "5db8b18cda7b70c3ba10d84ef14c04bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.0.1.jar",
          "url": "core-crypto-jvm-0.0.1.jar",
          "size": 6925102,
          "sha512": "27eb512ada7602293b2ab0edf190f3d6cb0e1a69d4a31675b54b4293086ef7b1ffc34b99bd8f36e951480c358a72f2d4fce284a5786518e13568b9c0110239fb",
          "sha256": "a6b4ecd10835e2cc5ccdc600df388b57ca3e3e5a591a4806c9803652c86306af",
          "sha1": "beedb023c96228d8c7f15c954d4680453f32d3db",
          "md5": "5db8b18cda7b70c3ba10d84ef14c04bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-crypto-jvm-0.0.1-sources.jar",
          "url": "core-crypto-jvm-0.0.1-sources.jar",
          "size": 6802934,
          "sha512": "382301242f04c74eade8d85abddf75791222f61502492c1e57e51e4601a8e8b25361bcc45e2aa6b4a7ac69ea3e3086fa696307905e54b34862b088f9fc435255",
          "sha256": "3c723cdd18496c08ddfe9b024196e420c06005dc50e69e12eff458f69df499c9",
          "sha1": "07cfe3dc417cc1a0b371451da08ad43a23959586",
          "md5": "4f9552a3f0379f51a8fefb99160915e8"
        }
      ]
    }
  ]
}
