{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wire",
    "module": "core-crypto-jvm",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.0.1.jar",
          "url": "core-crypto-jvm-0.0.1.jar",
          "size": 30875524,
          "sha512": "128b097fd9ed2f829c6aec1559d03ac7b986d557b0769702992fcf0e628db41fb1b5977eed6db244cf13af686720678e9e65b40148b1503ac5d151e327a6de54",
          "sha256": "c73be0b33bc76e520d8ca68490bf814207a99b7ba74cfa07b9dd01138f8f229a",
          "sha1": "e04edda699283ddc57886a00f6955bf1ba37db5a",
          "md5": "7028694476ca466a6c3c90187c2ed8c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.8.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-crypto-jvm-0.0.1.jar",
          "url": "core-crypto-jvm-0.0.1.jar",
          "size": 30875524,
          "sha512": "128b097fd9ed2f829c6aec1559d03ac7b986d557b0769702992fcf0e628db41fb1b5977eed6db244cf13af686720678e9e65b40148b1503ac5d151e327a6de54",
          "sha256": "c73be0b33bc76e520d8ca68490bf814207a99b7ba74cfa07b9dd01138f8f229a",
          "sha1": "e04edda699283ddc57886a00f6955bf1ba37db5a",
          "md5": "7028694476ca466a6c3c90187c2ed8c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-crypto-jvm-0.0.1-sources.jar",
          "url": "core-crypto-jvm-0.0.1-sources.jar",
          "size": 30753356,
          "sha512": "ae0f7c5418d855bbc1627b7da4184c4e02aa935218c719d54c84e2b3c016751272c99e62502b68bf4f7c5416590b6c57affef7555c1b83261297d81b1be66706",
          "sha256": "7805b8b667b67e900b5cb3e20e259eae39e2881996101c6d2a59c4a6291a6e7f",
          "sha1": "c21b2a6061a52fb7cf2c422a8896a5806870f38e",
          "md5": "16dbefcd81b98c0a4b03b317430c2877"
        }
      ]
    }
  ]
}
